language: cpp
os: osx
# osx_image: xcode9.3 # For Java 8
compiler: clang

addons:
  # To avoid being prompted when ssh'ing into sourceforge.
  ssh_known_hosts:
      # For uploading doxygen.
      - web.sourceforge.net
      # For deleting old doxygen.
      - shell.sourceforge.net
      # For uploading binaries.
      - frs.sourceforge.net
  # Using homebrew directly may not work because of Ruby versions; use the
  # Homebrew addon.
  # https://docs.travis-ci.com/user/installing-dependencies#installing-packages-on-macos
  homebrew:
    packages:
      - openblas
      - doxygen
    update: true

env: 
  global:
    - SWIG_VER=3.0.8
    - BTYPE=Release
    - NPROC=2
    - DEPLOY=yes
    - DOXY=on
    - WRAP=on
    - OSX_TARGET=10.10
#  matrix:
#    - BTYPE=Release NPROC=2 DEPLOY=yes DOXY=on WRAP=on OSX_TARGET=10.10

jobs:
  include:
    - stage: dependencies
      name: "opensim-core"
      script: bash .github/travis_dependencies.sh opensim-core
      if: commit_message =~ /(build deps|build opensim-core)/
    - stage: dependencies
      name: "adolc"
      script: bash .github/travis_dependencies.sh adolc
      if: commit_message =~ /(build deps|build adolc)/
    - stage: dependencies
      name: "casadi"
      script: bash .github/travis_dependencies.sh casadi
      if: commit_message =~ /(build deps|build casadi)/
    - stage: dependencies
      name: "eigen"
      script: bash .github/travis_dependencies.sh eigen
      if: commit_message =~ /(build deps|build eigen)/
    - stage: buildtest
      script: bash .github/travis_buildtest.sh
